### ISSUE TITLE
Fails to deploy

### ISSUE THREAD

**Issue by samwoolertonFosters** [fly-apps/hello_elixir#3]
Cloning this repo down (changing nothing at all) and following [the guide](https://fly.io/docs/getting-started/elixir/#install-flyctl-and-login) doesn’t deploy for me. Have tested in both Sydney and Virginia (the default) regions.

Here’s the final lines of the deploy
```
Running: `/app/bin/hello_elixir eval HelloElixir.Release.migrate` as nobody       
         2021/07/08 00:38:42 listening on [fdaa:0:2f24:a7b:ad6:f8da:1834:2]:22 (DNS: [fdaa::3]:53)
: not foundpp/bin/hello_elixir: /app/releases/0.1.0/env.sh: line 2:
         Main child exited normally with code: 127
         Starting clean up.
Error Release command failed, deployment aborted
```

Any thoughts on how to get this deployed, or whether I need to make changes to the repo before it’ll work?

**Comment by brainlid** [comment]
I just updated this demo repo for Phoenix 1.6, esbuild, and the latest fly configs.
