### ISSUE TITLE
Output of  "fly aps private"

### ISSUE THREAD

**Issue by gtaranti** [fly-apps/hello_elixir#7]
I used the script w/o success.
It didn't find the IP address.

I changed this part of the script :

` fly ips private | awk '(NR>1){ print $5 }'` 

and it WORKED! 

(changed $3 to $5)

**Comment by brainlid** [comment]
The `observer` script was completely reworked and now uses the `fly status --json` command. It requires the `jq` command to be present in the OS, which is a command line JSON parsing utility.
